### ISSUE TITLE
No module named 'signals' , when  i run "python manage.py syncdb"

### ISSUE THREAD

**Issue by maniachhz** [trojkat/doner#1]
Dear All,

I want to install doner with command 'python manage.py syncdb', then i got the errors:
```
import signals
ImportError:No module named 'signals'
```

My PC env:
```
python3.4
django-1.6.11
```

Can you tell me how to fix this problem? Thanks.

**Comment by maniachhz** [comment]
I fixed above problem with using Python2.7 instead of Python3.4.

Another problem, how to add new member? I can't find the link to add new member!

**Comment by trojkat** [comment]
For now you have to add users via django admin panel under `/admin/`

**Comment by maniachhz** [comment]
Thanks.
